# Generated by Django 6.0 on 2026-02-06 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('Deluxe', 'Deluxe Room'), ('Family', 'Family Room'), ('Suite', 'Luxury Suite')], max_length=20)),
                ('price_per_night', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='rooms/')),
            ],
        ),
        migrations.AddField(
            model_name='booking_table',
            name='check_in',
            field=models.DateField(default=datetime.date(2026, 2, 6)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking_table',
            name='check_out',
            field=models.DateField(default=datetime.date(2026, 2, 6)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking_table',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2026, 2, 6)),
            preserve_default=False,
        ),
    ]
