# Generated by Django 6.0 on 2026-02-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0002_room_booking_table_check_in_booking_table_check_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_table',
            name='total_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='t_persons',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='t_rooms',
            field=models.PositiveIntegerField(),
        ),
    ]
