# Generated by Django 6.0 on 2026-02-23 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0003_galleryimage'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='bookingapp__check_i_1deb19_idx',
        ),
        migrations.RemoveField(
            model_name='room',
            name='season_multiplier',
        ),
    ]
